Minor improvements

diff --git a/php/switch-php b/php/switch-php
--- a/php/switch-php
+++ b/php/switch-php
@@ -103,6 +103,8 @@ for extension in "${extensions[@]}"; do
     fi
 done
 
+# Enable the requested PHP version
+echo "Enabling PHP $PHP_VERSION"
 # Disable the currently enabled PHP version if it's not the target version
 enabled_php_version=$(ls /etc/apache2/mods-enabled | grep -oP '^php\d\.\d')
 
@@ -112,21 +114,17 @@ if [ -n "$enabled_php_version" ] && [ "$enabled_php_version" != "php$PHP_VERSION
 else
     echo "PHP $enabled_php_version is already the target version."
 fi
+a2enmod php$PHP_VERSION
 
-# Enable the requested PHP version
-echo "Enabling PHP $PHP_VERSION"
-a2enmod "php$PHP_VERSION"
-
-# Update the alternatives system to point to the desired PHP version for the CLI
 update-alternatives --set php "/usr/bin/php$PHP_VERSION"
 update-alternatives --set phar "/usr/bin/phar$PHP_VERSION"
 update-alternatives --set phar.phar "/usr/bin/phar.phar$PHP_VERSION"
 
-# Add APC for CLI - ensure it's added only once
 CLI_PHP_INI="/etc/php/$PHP_VERSION/cli/php.ini"
 if ! grep -q "apc.enable_cli=1" "$CLI_PHP_INI"; then
-    echo "apc.enable_cli=1" | tee -a "$CLI_PHP_INI"
+    echo "apc.enable_cli=1" | sudo tee -a "$CLI_PHP_INI"
 fi
+
 
 # Restart Apache to apply changes
 service apache2 restart || {
@@ -136,3 +134,61 @@ service apache2 restart || {
 
 echo "Switched to PHP $PHP_VERSION"
 echo "PHP CLI version switched"
+
+
+# Modify php.ini as needed
+echo "Modifying PHP configurations..."
+
+# Get total RAM and calculate 75%
+TOTAL_RAM=$(awk '/MemTotal/ {print $2}' /proc/meminfo) || exit 1
+RAM_75_PERCENT=$((TOTAL_RAM * 3 / 4 / 1024))M || RAM_75_PERCENT=1G
+
+desired_error_reporting="error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE & ~E_WARNING"
+desired_post_max_size="post_max_size = 1G"
+desired_upload_max_filesize="upload_max_filesize = 1G"
+desired_memory_limit="memory_limit = $RAM_75_PERCENT"
+desired_strict_mode="session.use_strict_mode = 1"
+desired_max_execution_time="max_execution_time = 300"
+
+for phpini in /etc/php/$PHP_VERSION/apache2/php.ini /etc/php/$PHP_VERSION/cli/php.ini; do
+    awk -v er="$desired_error_reporting" -v pms="$desired_post_max_size" \
+        -v umf="$desired_upload_max_filesize" -v ml="$desired_memory_limit" \
+        -v dsm="$desired_strict_mode" -v met="$desired_max_execution_time" \
+        '{
+        if ($0 ~ /^error_reporting[[:space:]]*=/) {print ";" $0 "\n" er; next}
+        if ($0 ~ /^post_max_size[[:space:]]*=/) {print ";" $0 "\n" pms; next}
+        if ($0 ~ /^upload_max_filesize[[:space:]]*=/) {print ";" $0 "\n" umf; next}
+        if ($0 ~ /^memory_limit[[:space:]]*=/) {print ";" $0 "\n" ml; next}
+        if ($0 ~ /^session.use_strict_mode[[:space:]]*=/) {print ";" $0 "\n" dsm; next}
+        if ($0 ~ /^max_execution_time[[:space:]]*=/) {print ";" $0 "\n" met; next}
+        print $0
+    }' $phpini >temp.ini && mv temp.ini $phpini
+done
+
+
+# Composer Setup
+echo "Checking for Composer..."
+if command -v composer &>/dev/null; then
+    echo "Composer is already installed. Updating..."
+    composer self-update
+else
+    echo "Installing Composer..."
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+    HASH=$(wget -q -O - https://composer.github.io/installer.sig)
+    echo "Installer hash: $HASH"
+    php -r "if (hash('SHA384', file_get_contents('composer-setup.php')) !== '$HASH') { unlink('composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }"
+    php composer-setup.php
+    if [ $? -ne 0 ]; then
+        echo "Failed to install Composer."
+    fi
+    php -r "unlink('composer-setup.php');"
+    mv composer.phar /usr/local/bin/composer
+fi
+
+
+
+# Restart Apache to apply changes
+service apache2 restart || {
+    echo "Failed to restart Apache. Please check the configuration."
+    exit 1
+}
